class Hw:
    BUFFERS_IN_BRAM = 0x8
    SAMPLES_PER_FLIT = 0x8
    BYTES_PER_SAMPLE = 0x2
    TIME_CORRECTION_COEFF = 1.1
    CPU_PAGE_SIZE=4096
    HW_INTEGRATOR_WINDOW_SIZE=1
    DDR_BPS_MAX = 500 * 1e6 * 8 * BYTES_PER_SAMPLE #Bytes per sec